fails:Exception#cause returns the active exception when an exception is raised
